from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^media/(?P<file_path>.+)$', views.serve_media_file, name='serve_media_file'),
    path('conversations/', views.conversations_list, name='conversations_list'),
    path('conversations/<int:conversation_id>/', views.conversation_detail, name='conversation_detail'),
    path('conversations/<int:conversation_id>/messages/', views.get_conversation_messages, name='conversation_messages'),
    path('conversations/create/', views.create_conversation, name='create_conversation'),
    path('conversations/<int:conversation_id>/add-participants/', views.add_group_participants, name='add_group_participants'),
    path('conversations/<int:conversation_id>/remove-participant/', views.remove_group_participant, name='remove_group_participant'),
    path('messages/', views.send_message, name='send_message'),
    path('upload-media/', views.upload_media, name='upload_media'),
    path('broadcast/', views.broadcast_message, name='broadcast_message'),
    path('search/', views.search, name='search'),
    path('mark-read/', views.mark_messages_read, name='mark_messages_read'),
    path('online-users/', views.get_online_users, name='get_online_users'),
    path('delete-message/', views.delete_message, name='delete_message'),
    path('delete-conversation/', views.delete_conversation, name='delete_conversation'),
    path('messages/<int:message_id>/read-receipts/', views.get_message_read_receipts, name='get_message_read_receipts'),
    path('messages/<int:message_id>/edit/', views.edit_message, name='edit_message'),
    path('messages/<int:message_id>/delete/', views.delete_message_api, name='delete_message_api'),
    path('helpdesk/requests/', views.get_helpdesk_requests, name='get_helpdesk_requests'),
    path('helpdesk/request/', views.create_helpdesk_request, name='create_helpdesk_request'),
    path('helpdesk/request/<int:request_id>/take/', views.take_helpdesk_request, name='take_helpdesk_request'),
    path('helpdesk/containers/', views.get_helpdesk_containers, name='get_helpdesk_containers'),
    path('helpdesk/container/', views.create_helpdesk_container, name='create_helpdesk_container'),
    path('helpdesk/container/<int:container_id>/take/', views.take_over_container, name='take_over_container'),
    path('helpdesk/take-over/<int:container_id>/', views.take_over_container, name='take_over_container_alt'),
    path('helpdesk/complete/<int:container_id>/', views.complete_container, name='complete_container'),
    path('helpdesk/task-chat/<int:container_id>/messages/', views.get_task_chat_messages, name='get_task_chat_messages'),
    path('helpdesk/task-chat/<int:container_id>/mark-read/', views.mark_task_chat_read, name='mark_task_chat_read'),
    path('helpdesk/work-status/', views.get_helpdesk_work_status, name='get_helpdesk_work_status'),
    path('helpdesk/data-table/', views.get_helpdesk_data_table, name='get_helpdesk_data_table'),
    path('it-membership/users/', views.it_membership_users, name='it_membership_users'),
    path('it-membership/update/', views.update_it_membership, name='update_it_membership'),
    path('it-membership/history/', views.it_membership_history, name='it_membership_history'),
]
